name: Setup Electron Template with Renderer
description: Initialize the Electron template with renderer package and dependencies

inputs:
  renderer-template:
    description: Define what vite template should be used to create renderer in case if renderer package doesn't exist
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "18.x"
        # Disable setup-node cache to avoid stale node_modules from Node 22
        cache: ""

    - name: Check if renderer directory exists
      id: check-renderer
      run: >-
        if [ -d "packages/renderer" ]; then
          echo "RENDERER_EXIST=true" >> $GITHUB_OUTPUT
        else
          echo "RENDERER_EXIST=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - run: |
        npm run create-renderer -- -- --template ${{inputs.renderer-template}}
        npm start --workspace @app/integrate-renderer
      shell: bash
      if: inputs.renderer-template != '' && steps.check-renderer.outputs.RENDERER_EXIST == 'false'

    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: npm-${{ runner.os }}-node18-${{ inputs.renderer-template }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          npm-${{ runner.os }}-node18-${{ inputs.renderer-template }}-

    - name: Clean workspace (remove incompatible node_modules)
      run: |
        echo "Cleaning npm cache..."
        npm cache clean --force
        echo "Removing node_modules directories..."
        rm -rf node_modules packages/*/node_modules 2>/dev/null || true
        echo "Cleanup complete"
      shell: bash

    - name: Install Dependencies
      run: |
        set -e
        if [ "${{ steps.check-renderer.outputs.RENDERER_EXIST }}" == "true" ] && [ -f "package-lock.json" ]; then
          echo "Using npm ci for existing project..."
          npm ci --prefer-offline --no-audit --progress=false
        else
          echo "Using npm install for new project..."
          npm install --prefer-offline --no-audit --progress=false
        fi
      shell: bash
      env:
        PYTHON: python
        msvs_version: 2022
