# ⚠️ DEPRECATED: This workflow has been integrated into ci.yml
# Semantic release is now handled automatically by the main CI workflow
# This file is kept for reference only and will not run

name: Release (Deprecated - Use CI Workflow)

on:
  workflow_dispatch: # Manual trigger only for testing

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  attestations: write

jobs:
  # Step 1: Determine if we should release
  analyze:
    runs-on: ubuntu-latest
    outputs:
      should-release: ${{ steps.check.outputs.should-release }}
      new-version: ${{ steps.check.outputs.new-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run semantic-release in dry-run mode
        id: check
        run: |
          # Run semantic-release in dry-run to check if release is needed
          OUTPUT=$(npx semantic-release --dry-run 2>&1 || true)
          echo "$OUTPUT"

          # Check if a new version would be published
          if echo "$OUTPUT" | grep -q "Published release"; then
            NEW_VERSION=$(echo "$OUTPUT" | grep -oP "Published release \K[0-9]+\.[0-9]+\.[0-9]+" | head -1)
            echo "should-release=true" >> $GITHUB_OUTPUT
            echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "✅ New release will be created: v$NEW_VERSION"
          else
            echo "should-release=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No release needed - no significant changes found"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  # Step 2: Build and test (reuse existing workflow)
  build-and-test:
    needs: analyze
    if: needs.analyze.outputs.should-release == 'true'
    uses: ./.github/workflows/compile-and-test.yml
    with:
      app-version: ${{ needs.analyze.outputs.new-version }}
      distribution-channel: main
      renderer-template: ""
    secrets: inherit

  # Step 3: Create release with semantic-release
  create-release:
    needs: [analyze, build-and-test]
    if: needs.analyze.outputs.should-release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: windows-main
          path: dist

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
